version: '3.8'

services:
  nginx:
    image: nginx
    volumes:
      - /docker/nginx/rank.conf:/etc/nginx/conf.d/rank.conf
      - .:/var/www/html/rank_api/
      - /docker/nginx/logs:/var/log/nginx
    ports:
      - "8080:80"
    environment:
      - NGINX_HOST=rank-api.localhost
      - NGINX_PORT=80
    networks:
      - rank-network

  mariadb:
    image: bitnami/mariadb:latest
    container_name: mariadb
    restart: always
    environment:
      ALLOW_EMPTY_PASSWORD: yes
      MARIADB_USER: testMySQL
      MARIADB_PASSWORD: testMySQL
      MARIADB_ROOT_PASSWORD: testMySQL
      MARIADB_DATABASE: rank
    ports:
      - "3307:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - rank-network

  redis:
    image: redis
    container_name: redis-rank
    restart: always
    ports:
      - "6379:6379"
    networks:
      - rank-network

  phpfpm:
    image: php:8.2-fpm
    container_name: phpfpm
    build:
      context: .
      dockerfile: docker/php/dockerFile
    working_dir: /var/www/html/rank_api
    volumes:
      - ./rank_api/:/var/www/html/rank_api/
    ports:
      - 9000:9000
    networks:
      - rank-network

networks:
  rank-network:
    external: false
    driver: bridge
